apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    name: nginx-service
    environment: dev
    #tier: DB
    #project: roboshop
spec:
  selector:
  # you should provide pod labels here
    app: nginx
   # tier: DB
    #project: roboshop
  ports:
  - name: http-port
    protocol: TCP
    # service port
    port: 80
    # pod port
    targetPort: 80